name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Npm install client
      run: |
        cd client
        npm install
    - name: Build client
      run: |
        cd client
        npm run build
    - name: Npm install server
      run: |
        cd server
        npm install
    - name: Check syntax server
      run: | 
        cd server/src
        node --check app.js
        node --check routes.js
        cd config
        node --check keys.js
        node --check passport.js
        cd ../controllers
        node --check AuthenticationController.js
        node --check ChatRoomController.js
        node --check SocketController.js
        cd ../models
        node --check Room.js
        node --check SocketUsers.js
        node --check User.js
